# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Straw Quick Dump
#'
#' fast C++ implementation of dump. Not as fully featured as the
#' Java version. Reads the .hic file, finds the appropriate matrix and slice
#' of data, and outputs as data.frame in sparse upper triangular format.
#' Currently only supporting matrices.
#' 
#' Usage: straw_R <NONE/VC/VC_SQRT/KR> <hicFile(s)> <chr1>[:x1:x2] <chr2>[:y1:y2] <BP/FRAG> <binsize>
#' 
#' @param argv string of arguments separated by spaces
#' @return Data.frame of a sparse matrix of data from hic file. x,y,counts
#' @export
straw_R <- function(argv) {
    .Call('_strawr_straw_R', PACKAGE = 'strawr', argv)
}

